
apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-configmap
  namespace: loja-veloz
data:
  DB_HOST: "postgres-service.loja-veloz.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "loja_veloz"
  DB_USER: "app_pedidos"
