apiVersion: v1
kind: Service
metadata:
  name: pedidos-service
  namespace: loja-veloz
  labels:
    app: pedidos-service
spec:
  type: ClusterIP # Exposição interna (segurança padrão)
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pedidos-service
